### ISSUE TITLE
Ansible module in network_backup.yml does not exist in execution environment

### ISSUE THREAD

**Issue by zcthompson** [network-automation/toolkit#38]
ERROR! couldn't resolve module/action 'ansible.controller.job_template'. This often indicates a misspelling, missing collection, or incorrect module path.

using network-workshop latest image.

**Comment by IPvSean** [comment]
@zcthompson investigating now, in general we prefer to use the ansible.controller collection versus the upstream community awx.awx, I am testing a fix to the network_ee now

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/pull/1911

please change to using the `quay.io/acme_corp/network_ee` and it will work
