### ISSUE TITLE
Exercise 6 Step 3 can't find backup.j2

### ISSUE THREAD

**Issue by mkbredem** [network-automation/toolkit#43]
Workshop Name: 9cvpk 

When running playbooks/network_backup.yml

TASK [Create restore job template] *********************************************
fatal: [rtr2]: FAILED! => {"changed": false, "msg": "Failed to update survey: Field 'spec' is missing from survey spec."}
{
  "msg": "Failed to update survey: Field 'spec' is missing from survey spec.",
  "invocation": {
    "module_args": {
      "name": "Network Automation - Restore",
      "job_type": "run",
      "inventory": "Workshop Inventory",
      "project": "Workshop Project",
      "playbook": "playbooks/network_restore.yml",
      "credential": "Workshop Credential",
      "survey_enabled": true,
      "survey_spec": {
        "changed": true,
        "backup_path": "/tmp/rtr2.txt",
        "date": "2023-08-22",
        "time": "20:06:27",
        "failed": false
      },
      "validate_certs": false,
      "execution_environment": "Default execution environment",
      "controller_host": "student1.9cvpk.example.opentlc.com",
      "controller_username": "admin",
      "controller_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "controller_oauthtoken": "",
      "verbosity": 0,
      "force_handlers": false,
      "timeout": 0,
      "job_slice_count": 1,
      "state": "present",
      "controller_config_file": null,
      "new_name": null,
      "copy_from": null,
      "description": null,
      "organization": null,
      "vault_credential": null,
      "credentials": null,
      "custom_virtualenv": null,
      "instance_groups": null,
      "forks": null,
      "limit": null,
      "extra_vars": null,
      "job_tags": null,
      "skip_tags": null,
      "start_at_task": null,
      "use_fact_cache": null,
      "host_config_key": null,
      "ask_diff_mode_on_launch": null,
      "ask_variables_on_launch": null,
      "ask_limit_on_launch": null,
      "ask_tags_on_launch": null,
      "ask_skip_tags_on_launch": null,
      "ask_job_type_on_launch": null,
      "ask_verbosity_on_launch": null,
      "ask_inventory_on_launch": null,
      "ask_credential_on_launch": null,
      "ask_execution_environment_on_launch": null,
      "ask_forks_on_launch": null,
      "ask_instance_groups_on_launch": null,
      "ask_job_slice_count_on_launch": null,
      "ask_labels_on_launch": null,
      "ask_timeout_on_launch": null,
      "become_enabled": null,
      "diff_mode": null,
      "allow_simultaneous": null,
      "scm_branch": null,
      "ask_scm_branch_on_launch": null,
      "webhook_service": null,
      "webhook_credential": null,
      "labels": null,
      "notification_templates_started": null,
      "notification_templates_success": null,
      "notification_templates_error": null,
      "prevent_instance_group_fallback": null
    }
  },
  "_ansible_no_log": null,
  "changed": false
}

**Comment by anshulbehl** [comment]
Hi @mkbredem This was fixed earlier today, can you do a sync on the project in automation controller and try again?

**Comment by mkbredem** [comment]
Thank you, that worked.

Thanks,

<https://red.ht/sig>

Michael Bredemeier, RHCE

Specialist Solutions Architect, Ansible

***@***.*** 813.523.8166
 Michael Bredemeier <https://www.linkedin.com/in/mbredemeier/>
RHEL
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-linux-platforms>
 | Hybrid Cloud <https://www.redhat.com/en> | Middleware
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-jboss-middleware>
 | Virtualization
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-virtualization>
 | PaaS
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-platform-as-a-service>
 | IaaS
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-infrastructure-as-a-service>
 | Storage
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-storage>
 | Cloud
<https://tracking.cirrusinsight.com/2100aa06-46c1-4867-9e04-5ea2fa59e95d/redhat-com-en-technologies-cloud-computing>
| Automation <https://www.redhat.com/en/technologies/management/ansible>
