### ISSUE TITLE
For Network Report Playbook - Task - Create HTML Report - fails with error dict object' has no attribute 'static_routes'

### ISSUE THREAD

**Issue by moffzilla** [network-automation/toolkit#47]
From the "Ansible Automation Platform 2 Networking Automation Workshop"
"Network-Report" Jobs (which calls playbooks/network_report_legacy.yml)  fail to generate a report 
Play Recap shows an error for the task:

TASK [../roles/build_report_container : Create HTML report] ********************

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'static_routes'. 'dict object' has no attribute 'static_routes'
fatal: [ansible-1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'static_routes'. 'dict object' has no attribute 'static_routes'"}
```
Attach the Debug output for the execution
[job_3.txt](https://github.com/network-automation/toolkit/files/14367057/job_3.txt)

**Comment by IPvSean** [comment]
fixed with https://github.com/network-automation/toolkit/pull/48
